#! /bin/bash
#create by beshoy semsem

function createProjectExpress {
if test -d projects/$1
then
$(zenity --error  --title="Reacter | Error" --text="you have project as same name. please choose onther name")
return 0
else
mkdir -p projects/$1
cd projects/$1 
createExpressServerCmd="express"
eval $createExpressServerCmd
mv public/javascripts/ public/js/
mv public/stylesheets/ public/css/
rm package.json
rm views/index.jade
clear
mkdir src
touch webpack.config.js
touch bower.json
touch .bowerrc
mkdir src/actions
mkdir src/components
mkdir src/containers
mkdir src/reducers
touch src/reducers/index.js
touch src/store.js
touch src/Main.js
mkdir -p public/js
packageName=$1
packageName=${packageName// /_}
packageName=`echo "${packageName}" | tr '[A-Z]' '[a-z]'`
# add package.json body#
cat <<EOT >> package.json
{
  "name": "$packageName",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "webpack": "webpack",
    "start": "webpack & node ./bin/www"
  },
  "dependencies": {
    "babel": "^6.5.2",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-decorators": "^6.13.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "express-history-api-fallback": "^2.1.0",
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-redux": "^5.0.1",
    "react-router": "^3.0.0",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "redux-promise-middleware": "^4.2.0",
    "redux-thunk": "^2.1.0",
    "serve-favicon": "~2.3.0",
    "webpack": "^1.14.0"
  }
}
EOT

# add bower.json body#
cat <<EOT >> bower.json
{
  "name": "$packageName",
  "description": "",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "jquery": "^2.2.3",
    "bootstrap": "^3.3.7",
    "font-awesome": "fontawesome#^4.6.1"
  }
}
EOT

# add bowerrc body#
cat <<EOT >> .bowerrc
{
  "directory" : "public/vendors"
}
EOT

# add index.jade body#
cat <<EOT >> views/index.jade
html
  head
    title= title     
    link(rel='stylesheet', href='/vendors/bootstrap/dist/css/bootstrap.min.css')
    link(rel='stylesheet', href='/vendors/font-awesome/css/font-awesome.min.css')
    link(rel='stylesheet', href='/css/style.css')
  body
    #app Reacter
    script(src='./vendors/jquery/dist/jquery.min.js')
    script(src='./js/app.js')
EOT

# add webpack.config.js body#
cat <<EOT >> webpack.config.js
var config = {
    entry: "./src/Main.js",

    output: {
        filename:"./public/js/app.js"
    },

    module: {
        loaders: [{
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: "babel",

            query: {
                presets: ["es2015", "react"],
                plugins:["transform-decorators-legacy"]
            }
        }]
    },

    watch:true
};

module.exports = config;
EOT


# add store.js body#
cat <<EOT >> src/store.js
import {createStore,applyMiddleware} from "redux"
import logger from 'redux-logger';
import thunk from 'redux-thunk';
import promise from 'redux-promise-middleware';
import reducers from './reducers';

const middleware=applyMiddleware(promise(),thunk,logger());

export default createStore(reducers,middleware);
EOT
# ================ #

# add reducers body#
cat <<EOT >> src/reducers/index.js
import {
    combineReducers
} from 'redux';
// reducers files
// end imports 
export default combineReducers({
    // end reducers object
})
EOT
# ================ #


# add Main.js body#
cat <<EOT >> src/Main.js
import React from "react";
import ReactDOM from "react-dom";
import Main from "./components/Main";
import {Provider} from 'react-redux';
import store from './store';
ReactDOM.render(
    <Provider store={store}>
        <Main/>
    </Provider>
,document.getElementById("app"));
EOT
# ================ #

# add main component body#
cat <<EOT >> src/components/Main.js
import React from "react";
import {connect} from 'react-redux';
// end imports

@connect((store)=>{
    return{
        // each key in this object will pass to component as props
    };
})
class Main extends React.Component{
    render (){        
        return (
            <div> $1 | Reacter Application </div>
        )
    }
}

module.exports=Main;

EOT
# ================ #

cd src
$(zenity --info  --title="Reacter | Info" --text="$1 project has created successfully")
return 1
fi
}
