#! /bin/bash
#create by beshoy semsem
#================= INCLUDE FILES =======================#
#source FILENAME
source createProject
source createProjectExpress
source createModel
source listProjects
source listModels
#================= MAIN FUNCTION =======================#
#used project
projectName="" 
clear
while true #main loop 
do 
    while true # projects menu loop
    do
        choice=$(zenity --title "Reacter | Project" --height "300" --text "Please Choose one from the below options" --list --radiolist --column "" --column "Options" True Create\ new\ project False Create\ new\ project\ with\ Express\ Server False List\ Projects False Use\ old\ project False Exit)
        case $choice in
        Create\ new\ project) #create
            projectName=$(zenity --entry --title="Reacter | Select Project" --text="Please enter Project name :")
            createProject  $projectName
            break    
        ;;
        Create\ new\ project\ with\ Express\ Server) #create
            projectName=$(zenity --entry --title="Reacter | Select Project" --text="Please enter Project name :")
            createProjectExpress  $projectName
            break    
        ;;
        List\ Projects) #list
            listProjects            
        ;;
        Use\ old\ project) #use old project 
            projectName=$(zenity --entry --title="Reacter | Select Project" --text="Please enter Project name :")
            # check if project exist
            if test -d projects/${projectName}
            then
            cd projects/${projectName}/src
            break
            else
            $(zenity --error --width="150" --title="404" --text="Project Not Found")
            fi
        ;; 
        Exit)
        exit 1
        ;;   
        esac
    done      
    # Now we have project 
    while true #models menu loop
    do
        choice=$(zenity --title "Reacter | Model" --text "Please Choose one from the below options" --list --radiolist --column "" --column "Options" False Create\ new\ model False List\ models True Change\ project)
        case $choice in
        Create\ new\ model) #create model
        modelName=$(zenity --entry --title="Reacter | Select Project" --text="Please enter model name :") 
        createModel  $modelName
        ;;
        List\ models) #list model
        listModels
        ;;
        Change\ project) #change project
        cd ./../../../ #back to root directory
        break # back to main menu loop
        ;;
        esac  
    done

done #end loop
