#! /bin/bash
#create by beshoy semsem
#================= INCLUDE FILES =======================#
#source FILENAME
source createProject
source createModel
#================= MAIN FUNCTION =======================#
#used project
projectName="" 
clear
while true
do
    echo "-Please, Choose one from the below options:"
    echo ""
    echo "1) Press 1 for creating new project "
    echo "2) Press 2 for use old project "
    echo ""  
    read -p "-Your choise is: " choice 
    clear   
    case $choice in
	1) #create
        echo -n "Please enter Project name  : "
        read projectName 
        createProject  $projectName
        break    
	;;
	2) #use old project 
        echo -n "Please enter Project name  : "
        read projectName 
        # check if project exist
        if test -d projects/${projectName}
        then
        cd projects/${projectName}
        break
        else
        echo "Error 404 :Project Not Found"
            sleep 2
            clear
        fi
	;;    
    esac
done      
clear
# Now we have project 
while true
do
    echo "-Please, Choose one from the below options:"
    echo ""
    echo "1) Press 1 for creating new model "
    echo ""  
    read -p "-Your choise is: " choice 
    clear   
    case $choice in
	1) #create model
	clear
	echo -n "Please enter model name  : "
	read modelName 
	createModel  $modelName
	;;
    esac  
    

done


