#! /bin/bash
#create by beshoy semsem

function listModels {
		clear
		echo   "=========Models=========="
			cd components
			for i in $(ls -d */); do echo ${i%%/}; done
			cd ../			
		echo  "=========================="
        echo ""
		echo  "Press Enter key to return back to menu ............."
        read key
        clear

}
