#! /bin/bash
#create by beshoy semsem

function listModels {
			cd components
			modelList=""
			for i in $(ls -d */); do echo modelList=$modelList${i%%/}"\n"; done
			cd ../			
			$(zenity --info --width="150" --title="Reacter | Models List" --text="$modelList")
}
