#! /bin/bash
#create by beshoy semsem

function listProjects {
			projectList=""
			cd projects/
			for i in $(ls -d */); do projectList=$projectList${i%%/}"\n"; done
			cd ../			
			$(zenity --info --width="150" --title="Reacter | Projects List" --text="$projectList")
}
